### PR TITLE
Cleanup UI

### PR DESCRIPTION
**Pull request by caco3**
- Beautify the html/js/csss code using https://www.jpkc.com/tools/beautify
- Beautify json using https://jsonformatter.curiousconcept.com
- Beautify yaml using https://onlineyamltools.com/prettify-yaml
- Added missing texts
- Removed redundant texts (will be filled in by i18n texts at runtime)

### CODE REVIEW

**Comment by caco3** [comment]
@tueddy, please first merge https://github.com/biologist79/ESPuino/pull/326

**Comment by caco3** [comment]
Issues are solved now -> PR is ready

**Comment by tueddy** [comment]
I'm generally not a fan of code beautification, but the rest fits well!

**Comment by caco3** [comment]
well, the issue is that most IDEs any way do some reformatting when you save the file. Before this PR, I always had to revert many lines to prevent them ending up in the PR. This is annoying and error prone.

**Comment by caco3** [comment]
I am not aware of such thing. But since I beautified the code (made the formating consistent) the IDEs (VS Code and PyCharm in my setup) did not reformat it anymore.

**Comment by tueddy** [comment]
@caco3 Yes, that's ok, but it also makes the code review more difficult because a lot of lines have changed..

**Comment by caco3** [comment]
> it also makes the code review more difficult because a lot of lines have changed..

Yes, I am aware of that, that's why I took it out of the Bootstrap 5 change.

BTW, did you know that Github can ignore whitespace changes in the diff?
grafik
This takes 50% of even more of the changes away.

**Pull request merged**
