### PR TITLE
Add support for PN532 RFID-Reader

### PR DESCRIPTION
**Pull request by datenzar**
Since I prefer the PN532 RFID-Reader (more versatile, can even be used with UART), I enhanced the code to support that chip.

Feel free to integrate and thanks a lot for this project!

### CODE REVIEW

**Comment by biologist79** [comment]
Hi,
thanks for your contribution. 
Need to get such a rfid-reader at first in order to test it. At least I'll need to change GPIO5 to a variable. 

But: what exactly is PN532 doing better in comparison to RC522? Have been testing PN5180 and it's advantage is better sensitivity (but needs some more GPIOs).

**Comment by datenzar** [comment]
Hi,

good point about the change of GPIO5. I used it instead of 21 since the pins all fit in one DuPont shell on the LOLIN32 but of course, it should be subject to configuration.

As far as the comparison to PN5180 is concerned, I cannot tell much. Compared to the standard RC522 it's the size that was most important to me (using [this one](https://www.amazon.de/ICQUANZX-Nahfeldkommunikationsleser-Modul-Kit-Schl%C3%BCsselkarte-DIY-Smartphone-Android-Handy/dp/B07VT431QZ/ref=sr_1_3?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=PN532+NFC&qid=1609846584&sr=8-3).

Apart from that, you can also connect it via UART (GPIO21/GPIO22) and hence save the SPI Pins for different uses.
I quickly measured the sensitivity and it starts to recognize the RFID tags with 3cm if nothing is in between.

**Comment by tueddy** [comment]
Hi,
i have all 3 readers tested, MFRC522, PN532 and PN5180.
MFRC522 and PN532 are very similar in RFID range and sensibility. There is no big difference.

The PN5180 brings  a huge step forward but as said before at cost of 2 more pins (and 3 if you want to wakeup from deep sleep with low power card detection LPCD).
The PN5180 can detect ISO-14443 cards >5 cm and ISO-15693 > 8cm.

**Comment by datenzar** [comment]
Thanks for your feedback @tueddy! I already ordered a PN5180 board from Aliexpress 2 weeks ago and it's on its way from China.

However, regarding the form factor, I couldn't find anything as small as that PN532 board. Maybe someone can give a hint.

**Comment by datenzar** [comment]
Hmm,  that's indeed weird. I don't work on a private repository. You can check the branch at https://github.com/datenzar/Tonuino-ESP32-I2S/tree/pn532

**Comment by biologist79** [comment]
Strange. Anyway, now I know where to get it from :-)

**Comment by biologist79** [comment]
I just ordered my pn532 a few days ago in .cn. Will take it's time to arrive... :-)

**Comment by biologist79** [comment]
My pn532 has finally arrived today. Will test within the next days...

**Comment by datenzar** [comment]
Very nice, Today I actually received a package of 2 as well. I guess they shared the same shipping container ;-)

**Pull request closed without merging**
