### PR TITLE
 fix crash in Bluetooth-sink mode (speaker)

### PR DESCRIPTION
**Pull request by tueddy**
Starting bluetooth audio in speaker mode (BT-sink) crashes, this is a regression coming from refactoring the logging ;-(

### CODE REVIEW

**Comment by fschrempf** [comment]
You seem to have based this off from your `tuedddy/dev` instead of `biologist79/dev`. Can you rebase, please?

**Comment by tueddy** [comment]
I will squash commit. This should add only the few changes and one entry.

**Comment by fschrempf** [comment]
> I will squash commit. This should add only the few changes and one entry, see tab "file changes"

No, please don't. It's really easy to do a rebase and force-push to create a clean PR that everyone can easily read and review. If you don't know how to do it, I'm glad to assist. If you are working with the CLI and `origin` is the upstream remote it's as simple as:

```
git fetch origin
git rebase origin/dev
gut push --force
```

Of course the "file changes" and the squash merge will show the correct result, but the Git history oft the PR doesn't and causes unnecessary confusion.

**Comment by tueddy** [comment]
@fschrempf  Thank you very much, I'll look at that with pleasure. 
But it's primarily about the content, are there any comments? Have you tested it?

**Comment by fschrempf** [comment]
> But it's primarily about the content, are there any comments? Have you tested it?

I'm always a bit hesitant to review or even look more closely at PRs if their Git history is messy and the description of the PR and the commits is lacking information.

Some might think of this as nitpicking, but it costs extra time and effort here to find out what the actual bug is that was trying to be fixed. As a reviewer I'd like to open the PR, read the description to get an idea what's going on, check the commits (subject and description) and see if they make sense and only then I look at actual code changes and see if they look good to me.

So I would really appreciate it if you could improve this in the future. Anyway, thanks for your efforts and now to the actual code:

I don't know for sure and I haven't tested it, but I guess the crash happened because of `a2dp_source` being `NULL` in case of sink mode when `connection_state_changed()` or `audio_state_changed()` callbacks get called!?

In that case I think there is a more elegant solution for this (only compile-tested) that just passes the pointer to the correct object via the callback state: https://github.com/fschrempf/ESPuino/commit/0c6c64e9bb19e8d10981bdce70c91fe4295d8da0.

**Comment by tueddy** [comment]
@fschrempf I understand your concerns but Githib is still a real brake at the moment.
With a squash commit, the master history is OK, just not in this then closed PR? Is that the only issue? I have tried your recommendations but they do not work:

grafik

I can delete the branch, create it again or commit it directly to the DEV. (but then this PR is lost in space).  
A lot of effort for 3 lines, we are in a hobby project here!
Maybe @laszloh can also create a new clean PR, because he caused this bug?

Edit: I will test your elegant minimal solution! Yes, in `connection_state_changed()` and `audio_state_changed()` the wrong object is selected (NULL).
You can also test it just by switching  to BT-Sink mode, e.g. via direct command in web-ui, connect your phone to ESPuino and just play some music..

**Comment by tueddy** [comment]
@fschrempf your bugfix works fine & it is elegant. Can you create a new PR & i will close it here?
Thank's!

**Comment by fschrempf** [comment]
> @fschrempf your bugfix works fine & it is elegant. Can you create a new PR & i will close it here?

Done: https://github.com/biologist79/ESPuino/pull/238

**Comment by fschrempf** [comment]
> With a squash commit, the master history is OK, just not in this then closed PR? Is that the only issue? 

IMHO, squashing commits using the GitHub "Squash & Merge" feature is almost always a bad idea as the resulting single commit has an automatically generated message that doesn't really fit in most cases.

And the main reason why the Git history in a PR needs to be clean is what I already explained [above](https://github.com/biologist79/ESPuino/pull/236#issuecomment-1538999384).

> I have tried your recommendations but they do not work:

This was only intended as a rough guide if you already use the CLI and have setup remotes for your own fork and the upstream repository. If you didn't use the CLI and have not worked with multiple remotes, I recommend to read [GitBook](https://git-scm.com/book/de/v2), especially the chapter on [working with remotes](https://git-scm.com/book/de/v2/Git-Grundlagen-Mit-Remotes-arbeiten).

> I can delete the branch, create it again or commit it directly to the DEV.

This is all not necessary and if you take the time to learn the "proper" workflow you will see that there are much easier and better ways to fix existing branches and PRs. You might want to have a look at the [chapter on rewriting the history](https://git-scm.com/book/de/v2/Git-Tools-Den-Verlauf-umschreiben) for more details.

Feel free to ping me (in the forum) if you have more questions or need any help!

**Comment by tueddy** [comment]
solved with #238

**Pull request closed without merging**
