### PR TITLE
Additional settings for button locking

### PR DESCRIPTION
**Pull request by fschrempf**
This includes two new settings related to locking of the controls/buttons:

* Add setting to lock controls by default
* Add setting to exclude rotary encoder from locking

### CODE REVIEW

**Comment by fschrempf** [comment]
On second thought I wonder if having unlocking the buttons via button itself is disabled on purpose? Is unlocking only intended to be done via modification tag?

**Comment by biologist79** [comment]
Locking and unlocking both indeed are only intended to be used by rfid-mod and/or mqtt. However, one can assign CMD_LOCK_BUTTONS_MOD to a button but when doing so there's no way back if pressed, hrhr.

**Comment by fschrempf** [comment]
> Locking and unlocking both indeed are only intended to be used by rfid-mod and/or mqtt. However, one can assign CMD_LOCK_BUTTONS_MOD to a button but when doing so there's no way back if pressed, hrhr.

Makes sense! I dropped the first commit from the PR.

**Comment by biologist79** [comment]
Added.
Thanks for your contribution.

**Pull request closed without merging**
